// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsSEzqTAFgDLHOj0zoDYuZzELPipwVSPY',
    appId: '1:973474869715:web:4b4e10a3dc230173cfbf26',
    messagingSenderId: '973474869715',
    projectId: 'tutorconnect-daf86',
    authDomain: 'tutorconnect-daf86.firebaseapp.com',
    storageBucket: 'tutorconnect-daf86.firebasestorage.app',
    measurementId: 'G-X2WPPPD9Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPNM13uc3FK40HFwZ9musr_B82GD45-8w',
    appId: '1:973474869715:android:a2cdd62a2f0e4613cfbf26',
    messagingSenderId: '973474869715',
    projectId: 'tutorconnect-daf86',
    storageBucket: 'tutorconnect-daf86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbF8XWExs4NEpe3qGJ_3ZmXVsPlRDkOAc',
    appId: '1:973474869715:ios:c101a510d47f75a0cfbf26',
    messagingSenderId: '973474869715',
    projectId: 'tutorconnect-daf86',
    storageBucket: 'tutorconnect-daf86.firebasestorage.app',
    iosBundleId: 'com.example.tutorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbF8XWExs4NEpe3qGJ_3ZmXVsPlRDkOAc',
    appId: '1:973474869715:ios:c101a510d47f75a0cfbf26',
    messagingSenderId: '973474869715',
    projectId: 'tutorconnect-daf86',
    storageBucket: 'tutorconnect-daf86.firebasestorage.app',
    iosBundleId: 'com.example.tutorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsSEzqTAFgDLHOj0zoDYuZzELPipwVSPY',
    appId: '1:973474869715:web:951ae80a5ff2b507cfbf26',
    messagingSenderId: '973474869715',
    projectId: 'tutorconnect-daf86',
    authDomain: 'tutorconnect-daf86.firebaseapp.com',
    storageBucket: 'tutorconnect-daf86.firebasestorage.app',
    measurementId: 'G-3QF7PCQGR4',
  );
}
