name: tutorconnect
description: Campus tutoring platform — connect students with peer tutors.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Location services
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0

  # State management
  provider: ^6.1.2

  # Image picking (device service)
  image_picker: ^1.0.7

  # Fonts
  google_fonts: ^6.2.1

  # Utilities
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1

  cupertino_icons: ^1.0.6
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Test mocks
  fake_cloud_firestore: ^2.5.1
  firebase_auth_mocks: ^0.13.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true